version: "3"
services:
  postgresdb:
    container_name: jpurchase-postgresdb
    image: library/postgres:13.2
    environment:
      POSTGRES_USER: jpurchaseuser1
      POSTGRES_PASSWORD: jpurchasepassword1
      POSTGRES_DB: jpurchase
    networks:
      - backend
    ports:
      - 5432:5432

  core:
    build:
      context: ./core
      dockerfile: ./DevDockerfile
    container_name: jpurchase-core-dev
    image: jpurchase-core:dev
    depends_on:
      - postgresdb
      - registry
    ports:
      - 8002:8002
      - 5002:5002
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/jpurchase
      SPRING_DATASOURCE_USERNAME: jpurchaseuser1
      SPRING_DATASOURCE_PASSWORD: jpurchasepassword1
    volumes:
      - "./core/target:/opt/project"

  registry:
    build:
      context: ./service-registry
      dockerfile: ./DevDockerfile
    container_name: service-registry-dev
    image: service-registry:dev
    ports:
      - 8001:8001
    networks:
      - backend
    volumes:
      - "./service-registry/target:/opt/project"

  gateway:
    build:
      context: ./zuul-gateway
      dockerfile: ./DevDockerfile
    container_name: jpurchase-gateway-dev
    image: jpurchase-gateway:dev
    depends_on:
      - core
      - registry
    ports:
      - 8003:8003
      - 5003:5003
    networks:
      - backend
      - frontend
    volumes:
      - "./zuul-gateway/target:/opt/project"

  frontend:
    build:
      context: ./ui
    container_name: jpurchase-ui
    image: jpurchase-ui
    depends_on:
      - gateway
    ports:
      - 80:80
    networks:
      - frontend
    volumes:
      - "./ui/default.conf:/etc/nginx/conf.d/default.conf"
      - "./ui/build/:/usr/share/nginx/html/"

#  frontend:
#    build:
#      context: ./ui
#      dockerfile: ./DevDockerfile
#    container_name: jpurchase-ui-dev
#    image: jpurchase-ui:dev
#    depends_on:
#      - core
#    ports:
#      - 4000:4000
#    networks:
#      - frontend
#    volumes:
#      - "./ui:/opt/project"
#
#  nginx-router:
#    container_name: nginx-router
#    image: nginx:1.17.1-alpine
#    depends_on:
#      - frontend
#    ports:
#      - 80:80
#    networks:
#      - frontend
#    volumes:
#      - ./ui/devDefault.conf:/etc/nginx/conf.d/default.conf


networks:
  frontend:
  backend: